//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Este código fuente fue generado automáticamente por xsd, Versión=4.0.30319.33440.
// 
namespace Hiberus.Actualizaciones.Schema {
    using System.Xml.Serialization;
    
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="my://HiberusUpdate")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="my://HiberusUpdate", IsNullable=false)]
    public partial class Tenant {
        
        private TenantCredentials credentialsField;
        
        private TenantSite[] sitesField;
        
        private string urlField;
        
        private string adminUrlField;
        
        /// <comentarios/>
        public TenantCredentials Credentials {
            get {
                return this.credentialsField;
            }
            set {
                this.credentialsField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Site", IsNullable=false)]
        public TenantSite[] Sites {
            get {
                return this.sitesField;
            }
            set {
                this.sitesField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Url {
            get {
                return this.urlField;
            }
            set {
                this.urlField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string AdminUrl {
            get {
                return this.adminUrlField;
            }
            set {
                this.adminUrlField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="my://HiberusUpdate")]
    public partial class TenantCredentials {
        
        private string accountField;
        
        private string passwordField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Account {
            get {
                return this.accountField;
            }
            set {
                this.accountField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="my://HiberusUpdate")]
    public partial class TenantSite {
        
        private TenantSiteWebs websField;
        
        private string urlField;
        
        /// <comentarios/>
        public TenantSiteWebs Webs {
            get {
                return this.websField;
            }
            set {
                this.websField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Url {
            get {
                return this.urlField;
            }
            set {
                this.urlField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="my://HiberusUpdate")]
    public partial class TenantSiteWebs {
        
        private TenantSiteWebsRootWeb rootWebField;
        
        private TenantSiteWebsWeb[] webField;
        
        private bool updateField;
        
        public TenantSiteWebs() {
            this.updateField = true;
        }
        
        /// <comentarios/>
        public TenantSiteWebsRootWeb RootWeb {
            get {
                return this.rootWebField;
            }
            set {
                this.rootWebField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute("Web")]
        public TenantSiteWebsWeb[] Web {
            get {
                return this.webField;
            }
            set {
                this.webField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool Update {
            get {
                return this.updateField;
            }
            set {
                this.updateField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="my://HiberusUpdate")]
    public partial class TenantSiteWebsRootWeb {
        
        private TenantSiteWebsRootWebSiteColumns siteColumnsField;
        
        private TenantSiteWebsRootWebContentTypes contentTypesField;
        
        private TenantSiteWebsRootWebLists listsField;
        
        private bool updateField;
        
        public TenantSiteWebsRootWeb() {
            this.updateField = true;
        }
        
        /// <comentarios/>
        public TenantSiteWebsRootWebSiteColumns SiteColumns {
            get {
                return this.siteColumnsField;
            }
            set {
                this.siteColumnsField = value;
            }
        }
        
        /// <comentarios/>
        public TenantSiteWebsRootWebContentTypes ContentTypes {
            get {
                return this.contentTypesField;
            }
            set {
                this.contentTypesField = value;
            }
        }
        
        /// <comentarios/>
        public TenantSiteWebsRootWebLists Lists {
            get {
                return this.listsField;
            }
            set {
                this.listsField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool Update {
            get {
                return this.updateField;
            }
            set {
                this.updateField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="my://HiberusUpdate")]
    public partial class TenantSiteWebsRootWebSiteColumns {
        
        private TenantSiteWebsRootWebSiteColumnsField[] fieldField;
        
        private string sourcePathField;
        
        private bool updateField;
        
        public TenantSiteWebsRootWebSiteColumns() {
            this.updateField = true;
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute("Field")]
        public TenantSiteWebsRootWebSiteColumnsField[] Field {
            get {
                return this.fieldField;
            }
            set {
                this.fieldField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string SourcePath {
            get {
                return this.sourcePathField;
            }
            set {
                this.sourcePathField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool Update {
            get {
                return this.updateField;
            }
            set {
                this.updateField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="my://HiberusUpdate")]
    public partial class TenantSiteWebsRootWebSiteColumnsField {
        
        private TenantSiteWebsRootWebSiteColumnsFieldRequiredWeb requiredWebField;
        
        private TenantSiteWebsRootWebSiteColumnsFieldRequiredList requiredListField;
        
        private string sourceXMLField;
        
        private bool updateAndPushChangesField;
        
        private string termGroupNameField;
        
        private string termSetNameField;
        
        private int lCIDField;
        
        private bool lCIDFieldSpecified;
        
        public TenantSiteWebsRootWebSiteColumnsField() {
            this.updateAndPushChangesField = true;
        }
        
        /// <comentarios/>
        public TenantSiteWebsRootWebSiteColumnsFieldRequiredWeb RequiredWeb {
            get {
                return this.requiredWebField;
            }
            set {
                this.requiredWebField = value;
            }
        }
        
        /// <comentarios/>
        public TenantSiteWebsRootWebSiteColumnsFieldRequiredList RequiredList {
            get {
                return this.requiredListField;
            }
            set {
                this.requiredListField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string SourceXML {
            get {
                return this.sourceXMLField;
            }
            set {
                this.sourceXMLField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool UpdateAndPushChanges {
            get {
                return this.updateAndPushChangesField;
            }
            set {
                this.updateAndPushChangesField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TermGroupName {
            get {
                return this.termGroupNameField;
            }
            set {
                this.termGroupNameField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TermSetName {
            get {
                return this.termSetNameField;
            }
            set {
                this.termSetNameField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int LCID {
            get {
                return this.lCIDField;
            }
            set {
                this.lCIDField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LCIDSpecified {
            get {
                return this.lCIDFieldSpecified;
            }
            set {
                this.lCIDFieldSpecified = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="my://HiberusUpdate")]
    public partial class TenantSiteWebsRootWebSiteColumnsFieldRequiredWeb {
        
        private string titleField;
        
        private string descriptionField;
        
        private string urlField;
        
        private uint lCIDField;
        
        private string siteOwnerLoginField;
        
        private string templateField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Url {
            get {
                return this.urlField;
            }
            set {
                this.urlField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint LCID {
            get {
                return this.lCIDField;
            }
            set {
                this.lCIDField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string SiteOwnerLogin {
            get {
                return this.siteOwnerLoginField;
            }
            set {
                this.siteOwnerLoginField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Template {
            get {
                return this.templateField;
            }
            set {
                this.templateField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="my://HiberusUpdate")]
    public partial class TenantSiteWebsRootWebSiteColumnsFieldRequiredList {
        
        private string nameField;
        
        private string templateTypeField;
        
        private bool enableVersioningField;
        
        private string urlPathField;
        
        private bool enableContentTypesField;
        
        private string webUrlField;
        
        public TenantSiteWebsRootWebSiteColumnsFieldRequiredList() {
            this.enableVersioningField = false;
            this.enableContentTypesField = false;
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TemplateType {
            get {
                return this.templateTypeField;
            }
            set {
                this.templateTypeField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool EnableVersioning {
            get {
                return this.enableVersioningField;
            }
            set {
                this.enableVersioningField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string UrlPath {
            get {
                return this.urlPathField;
            }
            set {
                this.urlPathField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool EnableContentTypes {
            get {
                return this.enableContentTypesField;
            }
            set {
                this.enableContentTypesField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string WebUrl {
            get {
                return this.webUrlField;
            }
            set {
                this.webUrlField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="my://HiberusUpdate")]
    public partial class TenantSiteWebsRootWebContentTypes {
        
        private TenantSiteWebsRootWebContentTypesContentType[] contentTypeField;
        
        private string sourcePathField;
        
        private bool updateField;
        
        public TenantSiteWebsRootWebContentTypes() {
            this.updateField = true;
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute("ContentType")]
        public TenantSiteWebsRootWebContentTypesContentType[] ContentType {
            get {
                return this.contentTypeField;
            }
            set {
                this.contentTypeField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string SourcePath {
            get {
                return this.sourcePathField;
            }
            set {
                this.sourcePathField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool Update {
            get {
                return this.updateField;
            }
            set {
                this.updateField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="my://HiberusUpdate")]
    public partial class TenantSiteWebsRootWebContentTypesContentType {
        
        private string sourceXMLField;
        
        private bool updateChildrenField;
        
        public TenantSiteWebsRootWebContentTypesContentType() {
            this.updateChildrenField = true;
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string SourceXML {
            get {
                return this.sourceXMLField;
            }
            set {
                this.sourceXMLField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool UpdateChildren {
            get {
                return this.updateChildrenField;
            }
            set {
                this.updateChildrenField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="my://HiberusUpdate")]
    public partial class TenantSiteWebsRootWebLists {
        
        private TenantSiteWebsRootWebListsList[] listField;
        
        private bool updateField;
        
        public TenantSiteWebsRootWebLists() {
            this.updateField = true;
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute("List")]
        public TenantSiteWebsRootWebListsList[] List {
            get {
                return this.listField;
            }
            set {
                this.listField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool Update {
            get {
                return this.updateField;
            }
            set {
                this.updateField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="my://HiberusUpdate")]
    public partial class TenantSiteWebsRootWebListsList {
        
        private TenantSiteWebsRootWebListsListContentTypes contentTypesField;
        
        private TenantSiteWebsRootWebListsListFolders foldersField;
        
        private string displayNameField;
        
        private string nameField;
        
        private string templateTypeField;
        
        private bool enableVersioningField;
        
        private string urlPathField;
        
        private string viewsSourcePathField;
        
        private bool enableContentTypesField;
        
        private bool enableContentTypesFieldSpecified;
        
        private bool enableFolderCreationField;
        
        private string draftVisibilityTypeField;
        
        private bool forceCheckOutField;
        
        private bool enableMinorVersionsField;
        
        private int majorVersionLimitField;
        
        private int majorWithMinorVersionsLimitField;
        
        public TenantSiteWebsRootWebListsList() {
            this.enableFolderCreationField = false;
            this.forceCheckOutField = false;
            this.enableMinorVersionsField = true;
            this.majorVersionLimitField = 0;
            this.majorWithMinorVersionsLimitField = 0;
        }
        
        /// <comentarios/>
        public TenantSiteWebsRootWebListsListContentTypes ContentTypes {
            get {
                return this.contentTypesField;
            }
            set {
                this.contentTypesField = value;
            }
        }
        
        /// <comentarios/>
        public TenantSiteWebsRootWebListsListFolders Folders {
            get {
                return this.foldersField;
            }
            set {
                this.foldersField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string DisplayName {
            get {
                return this.displayNameField;
            }
            set {
                this.displayNameField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TemplateType {
            get {
                return this.templateTypeField;
            }
            set {
                this.templateTypeField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool EnableVersioning {
            get {
                return this.enableVersioningField;
            }
            set {
                this.enableVersioningField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string UrlPath {
            get {
                return this.urlPathField;
            }
            set {
                this.urlPathField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ViewsSourcePath {
            get {
                return this.viewsSourcePathField;
            }
            set {
                this.viewsSourcePathField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool EnableContentTypes {
            get {
                return this.enableContentTypesField;
            }
            set {
                this.enableContentTypesField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool EnableContentTypesSpecified {
            get {
                return this.enableContentTypesFieldSpecified;
            }
            set {
                this.enableContentTypesFieldSpecified = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool EnableFolderCreation {
            get {
                return this.enableFolderCreationField;
            }
            set {
                this.enableFolderCreationField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string DraftVisibilityType {
            get {
                return this.draftVisibilityTypeField;
            }
            set {
                this.draftVisibilityTypeField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool ForceCheckOut {
            get {
                return this.forceCheckOutField;
            }
            set {
                this.forceCheckOutField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool EnableMinorVersions {
            get {
                return this.enableMinorVersionsField;
            }
            set {
                this.enableMinorVersionsField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(0)]
        public int MajorVersionLimit {
            get {
                return this.majorVersionLimitField;
            }
            set {
                this.majorVersionLimitField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(0)]
        public int MajorWithMinorVersionsLimit {
            get {
                return this.majorWithMinorVersionsLimitField;
            }
            set {
                this.majorWithMinorVersionsLimitField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="my://HiberusUpdate")]
    public partial class TenantSiteWebsRootWebListsListContentTypes {
        
        private TenantSiteWebsRootWebListsListContentTypesContentType[] contentTypeField;
        
        private TenantSiteWebsRootWebListsListContentTypesRemoveContentType[] removeContentTypeField;
        
        private bool updateField;
        
        public TenantSiteWebsRootWebListsListContentTypes() {
            this.updateField = true;
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute("ContentType")]
        public TenantSiteWebsRootWebListsListContentTypesContentType[] ContentType {
            get {
                return this.contentTypeField;
            }
            set {
                this.contentTypeField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute("RemoveContentType")]
        public TenantSiteWebsRootWebListsListContentTypesRemoveContentType[] RemoveContentType {
            get {
                return this.removeContentTypeField;
            }
            set {
                this.removeContentTypeField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool Update {
            get {
                return this.updateField;
            }
            set {
                this.updateField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="my://HiberusUpdate")]
    public partial class TenantSiteWebsRootWebListsListContentTypesContentType {
        
        private string idField;
        
        private string nameField;
        
        private bool setAsDefaultField;
        
        private bool searchContentTypeInSiteHierarchyField;
        
        public TenantSiteWebsRootWebListsListContentTypesContentType() {
            this.setAsDefaultField = false;
            this.searchContentTypeInSiteHierarchyField = true;
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool SetAsDefault {
            get {
                return this.setAsDefaultField;
            }
            set {
                this.setAsDefaultField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool SearchContentTypeInSiteHierarchy {
            get {
                return this.searchContentTypeInSiteHierarchyField;
            }
            set {
                this.searchContentTypeInSiteHierarchyField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="my://HiberusUpdate")]
    public partial class TenantSiteWebsRootWebListsListContentTypesRemoveContentType {
        
        private string nameField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="my://HiberusUpdate")]
    public partial class TenantSiteWebsRootWebListsListFolders {
        
        private TenantSiteWebsRootWebListsListFoldersFolder[] folderField;
        
        private bool updateField;
        
        public TenantSiteWebsRootWebListsListFolders() {
            this.updateField = true;
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute("Folder")]
        public TenantSiteWebsRootWebListsListFoldersFolder[] Folder {
            get {
                return this.folderField;
            }
            set {
                this.folderField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool Update {
            get {
                return this.updateField;
            }
            set {
                this.updateField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="my://HiberusUpdate")]
    public partial class TenantSiteWebsRootWebListsListFoldersFolder {
        
        private string nameField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="my://HiberusUpdate")]
    public partial class TenantSiteWebsWeb {
        
        private TenantSiteWebsWebSiteColumns siteColumnsField;
        
        private TenantSiteWebsWebContentTypes contentTypesField;
        
        private TenantSiteWebsWebLists listsField;
        
        private string urlField;
        
        private bool updateField;
        
        public TenantSiteWebsWeb() {
            this.updateField = true;
        }
        
        /// <comentarios/>
        public TenantSiteWebsWebSiteColumns SiteColumns {
            get {
                return this.siteColumnsField;
            }
            set {
                this.siteColumnsField = value;
            }
        }
        
        /// <comentarios/>
        public TenantSiteWebsWebContentTypes ContentTypes {
            get {
                return this.contentTypesField;
            }
            set {
                this.contentTypesField = value;
            }
        }
        
        /// <comentarios/>
        public TenantSiteWebsWebLists Lists {
            get {
                return this.listsField;
            }
            set {
                this.listsField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Url {
            get {
                return this.urlField;
            }
            set {
                this.urlField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool Update {
            get {
                return this.updateField;
            }
            set {
                this.updateField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="my://HiberusUpdate")]
    public partial class TenantSiteWebsWebSiteColumns {
        
        private TenantSiteWebsWebSiteColumnsField[] fieldField;
        
        private string sourcePathField;
        
        private bool updateField;
        
        public TenantSiteWebsWebSiteColumns() {
            this.updateField = true;
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute("Field")]
        public TenantSiteWebsWebSiteColumnsField[] Field {
            get {
                return this.fieldField;
            }
            set {
                this.fieldField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string SourcePath {
            get {
                return this.sourcePathField;
            }
            set {
                this.sourcePathField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool Update {
            get {
                return this.updateField;
            }
            set {
                this.updateField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="my://HiberusUpdate")]
    public partial class TenantSiteWebsWebSiteColumnsField {
        
        private TenantSiteWebsWebSiteColumnsFieldRequiredList requiredListField;
        
        private string sourceXMLField;
        
        private string termGroupNameField;
        
        private string termSetNameField;
        
        private int lCIDField;
        
        private bool lCIDFieldSpecified;
        
        /// <comentarios/>
        public TenantSiteWebsWebSiteColumnsFieldRequiredList RequiredList {
            get {
                return this.requiredListField;
            }
            set {
                this.requiredListField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string SourceXML {
            get {
                return this.sourceXMLField;
            }
            set {
                this.sourceXMLField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TermGroupName {
            get {
                return this.termGroupNameField;
            }
            set {
                this.termGroupNameField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TermSetName {
            get {
                return this.termSetNameField;
            }
            set {
                this.termSetNameField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int LCID {
            get {
                return this.lCIDField;
            }
            set {
                this.lCIDField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LCIDSpecified {
            get {
                return this.lCIDFieldSpecified;
            }
            set {
                this.lCIDFieldSpecified = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="my://HiberusUpdate")]
    public partial class TenantSiteWebsWebSiteColumnsFieldRequiredList {
        
        private string nameField;
        
        private string templateTypeField;
        
        private bool enableVersioningField;
        
        private string urlPathField;
        
        private bool enableContentTypesField;
        
        private string webUrlField;
        
        public TenantSiteWebsWebSiteColumnsFieldRequiredList() {
            this.enableVersioningField = false;
            this.enableContentTypesField = false;
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TemplateType {
            get {
                return this.templateTypeField;
            }
            set {
                this.templateTypeField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool EnableVersioning {
            get {
                return this.enableVersioningField;
            }
            set {
                this.enableVersioningField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string UrlPath {
            get {
                return this.urlPathField;
            }
            set {
                this.urlPathField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool EnableContentTypes {
            get {
                return this.enableContentTypesField;
            }
            set {
                this.enableContentTypesField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string WebUrl {
            get {
                return this.webUrlField;
            }
            set {
                this.webUrlField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="my://HiberusUpdate")]
    public partial class TenantSiteWebsWebContentTypes {
        
        private TenantSiteWebsWebContentTypesContentType[] contentTypeField;
        
        private string sourcePathField;
        
        private bool updateField;
        
        public TenantSiteWebsWebContentTypes() {
            this.updateField = true;
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute("ContentType")]
        public TenantSiteWebsWebContentTypesContentType[] ContentType {
            get {
                return this.contentTypeField;
            }
            set {
                this.contentTypeField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string SourcePath {
            get {
                return this.sourcePathField;
            }
            set {
                this.sourcePathField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool Update {
            get {
                return this.updateField;
            }
            set {
                this.updateField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="my://HiberusUpdate")]
    public partial class TenantSiteWebsWebContentTypesContentType {
        
        private string sourceXMLField;
        
        private bool updateChildrenField;
        
        public TenantSiteWebsWebContentTypesContentType() {
            this.updateChildrenField = true;
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string SourceXML {
            get {
                return this.sourceXMLField;
            }
            set {
                this.sourceXMLField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool UpdateChildren {
            get {
                return this.updateChildrenField;
            }
            set {
                this.updateChildrenField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="my://HiberusUpdate")]
    public partial class TenantSiteWebsWebLists {
        
        private TenantSiteWebsWebListsList[] listField;
        
        private bool updateField;
        
        public TenantSiteWebsWebLists() {
            this.updateField = true;
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute("List")]
        public TenantSiteWebsWebListsList[] List {
            get {
                return this.listField;
            }
            set {
                this.listField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool Update {
            get {
                return this.updateField;
            }
            set {
                this.updateField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="my://HiberusUpdate")]
    public partial class TenantSiteWebsWebListsList {
        
        private TenantSiteWebsWebListsListContentTypes[] contentTypesField;
        
        private TenantSiteWebsWebListsListFolders foldersField;
        
        private string displayNameField;
        
        private string nameField;
        
        private string templateTypeField;
        
        private bool enableVersioningField;
        
        private bool enableVersioningFieldSpecified;
        
        private string urlPathField;
        
        private bool enableContentTypesField;
        
        private bool enableContentTypesFieldSpecified;
        
        private bool enableFolderCreationField;
        
        private string viewsSourcePathField;
        
        private string draftVisibilityTypeField;
        
        private bool forceCheckOutField;
        
        private bool enableMinorVersionsField;
        
        private int majorVersionLimitField;
        
        private int majorWithMinorVersionsLimitField;
        
        public TenantSiteWebsWebListsList() {
            this.enableFolderCreationField = false;
            this.forceCheckOutField = false;
            this.enableMinorVersionsField = true;
            this.majorVersionLimitField = 0;
            this.majorWithMinorVersionsLimitField = 0;
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute("ContentTypes")]
        public TenantSiteWebsWebListsListContentTypes[] ContentTypes {
            get {
                return this.contentTypesField;
            }
            set {
                this.contentTypesField = value;
            }
        }
        
        /// <comentarios/>
        public TenantSiteWebsWebListsListFolders Folders {
            get {
                return this.foldersField;
            }
            set {
                this.foldersField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string DisplayName {
            get {
                return this.displayNameField;
            }
            set {
                this.displayNameField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TemplateType {
            get {
                return this.templateTypeField;
            }
            set {
                this.templateTypeField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool EnableVersioning {
            get {
                return this.enableVersioningField;
            }
            set {
                this.enableVersioningField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool EnableVersioningSpecified {
            get {
                return this.enableVersioningFieldSpecified;
            }
            set {
                this.enableVersioningFieldSpecified = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string UrlPath {
            get {
                return this.urlPathField;
            }
            set {
                this.urlPathField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool EnableContentTypes {
            get {
                return this.enableContentTypesField;
            }
            set {
                this.enableContentTypesField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool EnableContentTypesSpecified {
            get {
                return this.enableContentTypesFieldSpecified;
            }
            set {
                this.enableContentTypesFieldSpecified = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool EnableFolderCreation {
            get {
                return this.enableFolderCreationField;
            }
            set {
                this.enableFolderCreationField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ViewsSourcePath {
            get {
                return this.viewsSourcePathField;
            }
            set {
                this.viewsSourcePathField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string DraftVisibilityType {
            get {
                return this.draftVisibilityTypeField;
            }
            set {
                this.draftVisibilityTypeField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool ForceCheckOut {
            get {
                return this.forceCheckOutField;
            }
            set {
                this.forceCheckOutField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool EnableMinorVersions {
            get {
                return this.enableMinorVersionsField;
            }
            set {
                this.enableMinorVersionsField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(0)]
        public int MajorVersionLimit {
            get {
                return this.majorVersionLimitField;
            }
            set {
                this.majorVersionLimitField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(0)]
        public int MajorWithMinorVersionsLimit {
            get {
                return this.majorWithMinorVersionsLimitField;
            }
            set {
                this.majorWithMinorVersionsLimitField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="my://HiberusUpdate")]
    public partial class TenantSiteWebsWebListsListContentTypes {
        
        private TenantSiteWebsWebListsListContentTypesContentType[] contentTypeField;
        
        private TenantSiteWebsWebListsListContentTypesRemoveContentType[] removeContentTypeField;
        
        private bool updateField;
        
        public TenantSiteWebsWebListsListContentTypes() {
            this.updateField = true;
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute("ContentType")]
        public TenantSiteWebsWebListsListContentTypesContentType[] ContentType {
            get {
                return this.contentTypeField;
            }
            set {
                this.contentTypeField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute("RemoveContentType")]
        public TenantSiteWebsWebListsListContentTypesRemoveContentType[] RemoveContentType {
            get {
                return this.removeContentTypeField;
            }
            set {
                this.removeContentTypeField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool Update {
            get {
                return this.updateField;
            }
            set {
                this.updateField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="my://HiberusUpdate")]
    public partial class TenantSiteWebsWebListsListContentTypesContentType {
        
        private string idField;
        
        private string nameField;
        
        private bool setAsDefaultField;
        
        private string documentTemplatePathField;
        
        private bool searchContentTypeInSiteHierarchyField;
        
        public TenantSiteWebsWebListsListContentTypesContentType() {
            this.setAsDefaultField = false;
            this.searchContentTypeInSiteHierarchyField = true;
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool SetAsDefault {
            get {
                return this.setAsDefaultField;
            }
            set {
                this.setAsDefaultField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string DocumentTemplatePath {
            get {
                return this.documentTemplatePathField;
            }
            set {
                this.documentTemplatePathField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool SearchContentTypeInSiteHierarchy {
            get {
                return this.searchContentTypeInSiteHierarchyField;
            }
            set {
                this.searchContentTypeInSiteHierarchyField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="my://HiberusUpdate")]
    public partial class TenantSiteWebsWebListsListContentTypesRemoveContentType {
        
        private string nameField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="my://HiberusUpdate")]
    public partial class TenantSiteWebsWebListsListFolders {
        
        private TenantSiteWebsWebListsListFoldersFolder folderField;
        
        private bool updateField;
        
        public TenantSiteWebsWebListsListFolders() {
            this.updateField = true;
        }
        
        /// <comentarios/>
        public TenantSiteWebsWebListsListFoldersFolder Folder {
            get {
                return this.folderField;
            }
            set {
                this.folderField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool Update {
            get {
                return this.updateField;
            }
            set {
                this.updateField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="my://HiberusUpdate")]
    public partial class TenantSiteWebsWebListsListFoldersFolder {
        
        private TenantSiteWebsWebListsListFoldersFolderAssociatedContentTypes associatedContentTypesField;
        
        private string nameField;
        
        /// <comentarios/>
        public TenantSiteWebsWebListsListFoldersFolderAssociatedContentTypes AssociatedContentTypes {
            get {
                return this.associatedContentTypesField;
            }
            set {
                this.associatedContentTypesField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="my://HiberusUpdate")]
    public partial class TenantSiteWebsWebListsListFoldersFolderAssociatedContentTypes {
        
        private TenantSiteWebsWebListsListFoldersFolderAssociatedContentTypesAsignedContentType[] asignedContentTypeField;
        
        private string orderByField;
        
        private bool updateField;
        
        public TenantSiteWebsWebListsListFoldersFolderAssociatedContentTypes() {
            this.orderByField = "Ascending";
            this.updateField = true;
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute("AsignedContentType")]
        public TenantSiteWebsWebListsListFoldersFolderAssociatedContentTypesAsignedContentType[] AsignedContentType {
            get {
                return this.asignedContentTypeField;
            }
            set {
                this.asignedContentTypeField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("Ascending")]
        public string OrderBy {
            get {
                return this.orderByField;
            }
            set {
                this.orderByField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool Update {
            get {
                return this.updateField;
            }
            set {
                this.updateField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="my://HiberusUpdate")]
    public partial class TenantSiteWebsWebListsListFoldersFolderAssociatedContentTypesAsignedContentType {
        
        private string nameField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
}
